### ISSUE TITLE
Improve `README` with clear details on what the code is about.

### ISSUE THREAD

**Issue by Ashrockzzz2003** [viswa4403/LineScanAnalyzer#1]
Adding the following to `README` will improve understanding of the code and its purpose.

- [x] The problem statement.
- [x] Why parallel?
- [x] Explain code.

**Comment by viswa4403** [comment]
Hi Ashwin,

I have added the problem statement and the necessity of processing in parallel in the README file. Additionally, I have explained the code through comments for better understanding.

Thanks @Ashrockzzz2003
